# Generated by Django 5.2.5 on 2025-09-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authlinkingtoken_authprovider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authprovider',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='authprovider',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthLinkingToken',
        ),
        migrations.DeleteModel(
            name='AuthProvider',
        ),
    ]
